- name: Install unattended-upgrades
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - unattended-upgrades
      - apt-config-auto-update

- name: Configure unattended-upgrades
  become: true
  ansible.builtin.template:
    mode: "0644"
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  notify:
    - Restart unattended-upgrades
