- name: Setup certbot
  become: true
  changed_when: false
  ansible.builtin.shell:
    cmd: |
      certbot certonly \
      --dns-cloudflare \
      --dns-cloudflare-credentials ~/.secrets/cloudflare.ini \
      -d {{ certbot_host }} \
      -m {{ certbot_email }} \
      --agree-tos \
      --no-eff-email \
      --non-interactive \
      --no-redirect
