services:
  npm:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    network_mode: host
    volumes:
      - ${NPM_HOME}/data:/data
      - ${CERT_HOME}:/etc/letsencrypt
    dns:
      - ${UPSTREAM_DNS}