version: '3.8'
services:
  forever-stranded:
    image: itzg/minecraft-server:java21-alpine
    container_name: cobblemon
    user: 1600:1600
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - TYPE=MODRINTH
      - MODRINTH_MODPACK=cobblemon-fabric
      - EULA=true
      - INIT_MEMORY=1G
      - MAX_MEMORY=8G
      - ENABLE_ROLLING_LOGS=true
    volumes:
      - /data/minecraft/cobblemon:/data