# Install htop
- name: Install rsync
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - rsync

# Copy configuration
- name: Configure rsync
  become: true
  ansible.builtin.copy:
    mode: "0644"
    src: rsyncd.conf
    dest: /etc/rsyncd.conf

# Ensure rsyncd is stopped by default
- name: Stop + disable rsync
  become: true
  ansible.builtin.service:
    enabled: false
    name: rsync
    state: stopped
