postfix_relayhost: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62666136653336396636303762656163313638663136333736303034653064663232623763396364
  6337633934316138326435336635623665636136636434380a386131623032306335623737333066
  36356561613666393364373762343537303237313866343864323764633936653032333038316664
  3863653163633331310a653261643830616630336232306361323932336231643837343865376562
  32396266303632373139643830376363393835313636646161383662313730616633
