certbot_host: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61326464383064373830353333633464366139383664336639663738353562656436613738663231
  3465363533373366353537336131306166383834333938660a626434316435353031633563666532
  64613263353064323334343639393832313336326135303631323432343663666465383965313333
  6533346139353966390a353063626433366136336138653934353864353132336138393065636261
  3335
certbot_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33346330613463303537376666333534363365613637346564343037643566653836343430616539
  3865323262633165626463656133613939373863646137380a613238663137336366356539626238
  38613536356462333062373433343365326565323835353035643833313731306430343762636464
  3035353137373939340a383237656238306437323334326662636132623235363336616337616435
  36643063353934306136633464386633323136383466626266353535623531306339
