unattended_upgrades_report_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65313236353663323466633633653930626433356262383165373365613366336336303561376132
  6236313634303935633264666336646662633664383466640a323933613135383365613334313365
  64373961343963663362663338653934623361663739366237393636336334623366383765393137
  3561656630306165330a333663313666393432646637303065363830363039333765636264306463
  37306637613432343865366235636437323934653265663262653037396163346563653837383161
  3763653735656363343162386364613035653935663662646363
unattended_upgrades_email_policy: on-change
